[package]
name = "tinue-finder"
version = "0.1.0"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taik = { git = "https://github.com/MortenLohne/taik", branch = "f-generic-size" }
board-game-traits = "0.1"
pgn-traits = "0.1.1"
arrayvec = "0.5.1"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"

[dependencies.rusqlite]
version = "0.24.0"
features = ["bundled"] # necessary for windows