[package]
name = "tinue-finder"
version = "0.1.0"
authors = ["Morten Lohne <lohnemorten@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taik = { git = "https://github.com/MortenLohne/taik", branch = "f-generic-size" }
board-game-traits = "0.1"
pgn-traits = "0.1.1"
arrayvec = "0.5.1"